In [1]:
import numpy as np

In [4]:
# Crear arreglo de 1 dimension con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print('Arreglo 1D:', arr1)
print('Forma(shape):',arr1.shape)
print('Tipos de datos (dtype):', arr1.dtype)

Arreglo 1D: [1 2 3 4 5 6]
Forma(shape): (6,)
Tipos de datos (dtype): int64


In [5]:
# Cambiar la forma del arreglo a una matriz de 2x3
arr2 = arr1.reshape((2,3))
print('Arreglo 2D:\n', arr2)
print('Forma(shape):',arr2.shape)
print('Tipos de datos (dtype):', arr2.dtype)

Arreglo 2D:
 [[1 2 3]
 [4 5 6]]
Forma(shape): (2, 3)
Tipos de datos (dtype): int64


In [6]:
# Crear una matriz con forma (4,4) con numeros aleatorios ente 0 y 1
matrix = np.random.rand(4,4)
print('Arreglo 4D:\n', matrix)
print('Forma(shape):',matrix.shape)
print('Tipos de datos (dtype):', matrix.dtype)

Arreglo 4D:
 [[0.89164778 0.97688957 0.17666809 0.69178123]
 [0.08879268 0.57853041 0.37822428 0.04002377]
 [0.6761839  0.37815221 0.35690844 0.79250173]
 [0.14961592 0.18345476 0.41016544 0.49615012]]
Forma(shape): (4, 4)
Tipos de datos (dtype): float64


In [7]:
data = np.array([10, 20, 30, 40, 50])

# Calcula la media y la desviación estándar
mean = np.mean(data)
std = np.std(data)

# Aplica la normalización Z-score
normalized_data = (data - mean) / std

print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
